language: node_js
node_js:
  - '10'
script:
  - npm run lint
  - npm run test
before_deploy:
  - npm run ci-build
deploy:
  provider: npm
  email: danhaung1202@gmail.com
  api_key: $API_KEY
  on:
    branch: master
  skip_cleanup: true
