language: node_js
node_js:
  - '10'
stages:
  - name: publish
    if: branch = master
jobs:
  include:
    - stage: publish
      name: npm publish
      script: 
        - npm run ci-build
        - npm run ci-publish
    - script: 
        - npm run ci-build:docs
        - ci-publish:docs
      name: gitHub pages